# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f1583d996bfacc27e1314a91930f04a2"
name = "Test-assessment"
handle = "test-assessment-2"
application_url = "https://aqua-competitive-cylinder-calendars.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,write_checkouts,write_customers,write_draft_orders,write_products"

[auth]
redirect_urls = [
  "https://aqua-competitive-cylinder-calendars.trycloudflare.com/auth/callback",
  "https://aqua-competitive-cylinder-calendars.trycloudflare.com/auth/shopify/callback",
  "https://aqua-competitive-cylinder-calendars.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
